version: '3.8'
services:
  nginx:
    container_name: nginx
    build:
      context: ./docker/nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
    depends_on:
      - php
      - mariadb

  php:
    container_name: php
    build:
      context: ./docker/php
    volumes:
      - .:/var/www
    expose:
      - 9000
    depends_on:
      - mariadb

  mariadb:
    container_name: mariadb
    restart: always
    build:
      context: ./docker/mariadb
    environment:
      MARIADB_ALLOW_EMPTY_PASSWORD: "true"
      MARIADB_ROOT_PASSWORD: "${MARIADB_ROOT_PASSWORD}"
      MARIADB_DATABASE: "${MARIADB_DATABASE}"
      MARIADB_USER: "${MARIADB_USER}"
      MARIADB_PASSWORD: "${MARIADB_PASSWORD}"
    ports:
      - "8083:3306"
    volumes:
      - ./data/db:/var/lib/mysql

  adminer:
    container_name: adminer
    restart: always
    build:
      context: ./docker/adminer
    ports:
      - "8082:8080"
    depends_on:
      - mariadb
